const EMOJIS = {
  // ── PRODUITS LAITIERS ──
  lait: "🥛",
  "lait entier": "🥛",
  "lait demi": "🥛",
  "lait ecreme": "🥛",
  "lait vegetal": "🥛",
  "lait amande": "🥛",
  "lait soja": "🥛",
  "lait avoine": "🥛",
  fromage: "🧀",
  emmental: "🧀",
  gruyere: "🧀",
  comté: "🧀",
  comte: "🧀",
  camembert: "🧀",
  brie: "🧀",
  roquefort: "🧀",
  cheddar: "🧀",
  mozzarella: "🧀",
  parmesan: "🧀",
  reblochon: "🧀",
  raclette: "🧀",
  chevre: "🧀",
  feta: "🧀",
  gouda: "🧀",
  edam: "🧀",
  munster: "🧀",
  oeuf: "🥚",
  oeufs: "🥚",
  beurre: "🧈",
  margarine: "🧈",
  creme: "🥛",
  "creme fraiche": "🥛",
  "creme liquide": "🥛",
  chantilly: "🥛",
  yaourt: "🍶",
  yogourt: "🍶",
  "yaourt nature": "🍶",
  "yaourt grec": "🍶",
  "fromage blanc": "🍶",
  faisselle: "🍶",
  skyr: "🍶",
  "petit suisse": "🍶",
  "dessert lacte": "🍮",
  flan: "🍮",
  mousse: "🍮",
  "creme dessert": "🍮",
  liégeois: "🍶",

  // ── VIANDES ──
  viande: "🥩",
  boeuf: "🥩",
  beef: "🥩",
  steak: "🥩",
  entrecote: "🥩",
  "cote de boeuf": "🥩",
  roti: "🥩",
  "roti de boeuf": "🥩",
  haché: "🥩",
  hache: "🥩",
  "steak hache": "🥩",
  veau: "🥩",
  porc: "🥩",
  "cote de porc": "🥩",
  "filet de porc": "🥩",
  agneau: "🥩",
  gigot: "🥩",
  "cote agneau": "🥩",
  poulet: "🍗",
  "blanc de poulet": "🍗",
  "cuisses de poulet": "🍗",
  escalope: "🍗",
  dinde: "🍗",
  canard: "🍗",
  magret: "🍗",
  lapin: "🐰",
  chevreau: "🥩",

  // ── CHARCUTERIE ──
  jambon: "🥓",
  "jambon blanc": "🥓",
  "jambon cru": "🥓",
  prosciutto: "🥓",
  serrano: "🥓",
  chorizo: "🌶️",
  salami: "🥓",
  pepperoni: "🥓",
  lardons: "🥓",
  bacon: "🥓",
  pancetta: "🥓",
  saucisse: "🌭",
  saucisson: "🌭",
  merguez: "🌭",
  chipolata: "🌭",
  knack: "🌭",
  boudin: "🌭",
  pate: "🫙",
  rillette: "🫙",
  terrine: "🫙",
  mortadelle: "🥓",
  bresaola: "🥓",

  // ── POISSONS & FRUITS DE MER ──
  poisson: "🐟",
  saumon: "🐟",
  thon: "🐟",
  sardine: "🐟",
  maquereau: "🐟",
  cabillaud: "🐟",
  lieu: "🐟",
  sole: "🐟",
  daurade: "🐟",
  bar: "🐟",
  truite: "🐟",
  hareng: "🐟",
  anchois: "🐟",
  tilapia: "🐟",
  crevette: "🦐",
  gambas: "🦐",
  homard: "🦞",
  langouste: "🦞",
  crabe: "🦀",
  moule: "🦪",
  huitre: "🦪",
  coquille: "🦪",
  palourde: "🦪",
  seiche: "🦑",
  calamars: "🦑",
  poulpe: "🐙",
  surimi: "🦀",
  colin: "🐟",

  // ── FECULENTS & CEREALES ──
  pates: "🍝",
  pasta: "🍝",
  spaghetti: "🍝",
  tagliatelle: "🍝",
  penne: "🍝",
  fusilli: "🍝",
  rigatoni: "🍝",
  lasagne: "🍝",
  gnocchi: "🍝",
  ravioli: "🍝",
  tortellini: "🍝",
  linguine: "🍝",
  riz: "🍚",
  "riz basmati": "🍚",
  "riz long": "🍚",
  "riz rond": "🍚",
  "riz complet": "🍚",
  risotto: "🍚",
  "riz sauvage": "🍚",
  farine: "🌾",
  "farine de ble": "🌾",
  "farine complete": "🌾",
  fecule: "🌾",
  maizena: "🌾",
  semoule: "🌾",
  polenta: "🌾",
  quinoa: "🌾",
  boulgour: "🌾",
  epeautre: "🌾",
  orge: "🌾",
  cereales: "🥣",
  granola: "🥣",
  muesli: "🥣",
  avoine: "🥣",
  "corn flakes": "🥣",
  flocons: "🥣",
  pain: "🍞",
  "pain de mie": "🍞",
  "pain complet": "🍞",
  "pain sans gluten": "🍞",
  baguette: "🥖",
  ficelle: "🥖",
  "pain campagne": "🥖",
  brioche: "🥐",
  croissant: "🥐",
  "pain au chocolat": "🥐",
  viennoiserie: "🥐",
  "pain aux raisins": "🥐",
  biscottes: "🍞",
  crackers: "🍘",
  "galette de riz": "🍘",
  lentilles: "🍲",
  "lentilles vertes": "🍲",
  "lentilles corail": "🍲",
  "pois chiches": "🫘",
  "haricots rouges": "🫘",
  "haricots blancs": "🫘",
  flageolets: "🫘",
  feves: "🫘",
  "pois casses": "🫘",

  // ── FRUITS ──
  pomme: "🍎",
  "pomme golden": "🍎",
  "pomme granny": "🍎",
  "pomme fuji": "🍎",
  banane: "🍌",
  orange: "🍊",
  mandarine: "🍊",
  clémentine: "🍊",
  clementine: "🍊",
  pamplemousse: "🍊",
  citron: "🍋",
  "citron vert": "🍋",
  lime: "🍋",
  fraise: "🍓",
  framboise: "🍓",
  mure: "🫐",
  myrtille: "🫐",
  cassis: "🫐",
  groseille: "🍓",
  raisin: "🍇",
  "raisin blanc": "🍇",
  "raisin noir": "🍇",
  poire: "🍐",
  peche: "🍑",
  nectarine: "🍑",
  abricot: "🍑",
  prune: "🍑",
  cerise: "🍒",
  mangue: "🥭",
  ananas: "🍍",
  melon: "🍈",
  pasteque: "🍉",
  kiwi: "🥝",
  figue: "🍈",
  datte: "🍈",
  avocat: "🥑",
  "noix de coco": "🥥",
  litchi: "🍈",
  goyave: "🍈",
  papaye: "🍈",
  "fruit de la passion": "🍈",
  grenade: "🍎",

  // ── LEGUMES ──
  tomate: "🍅",
  "tomate cerise": "🍅",
  "tomate grappe": "🍅",
  carotte: "🥕",
  "carotte rapee": "🥕",
  brocoli: "🥦",
  "chou fleur": "🥦",
  chou: "🥬",
  "chou rouge": "🥬",
  "chou vert": "🥬",
  "chou blanc": "🥬",
  "chou kale": "🥬",
  salade: "🥗",
  laitue: "🥗",
  scarole: "🥗",
  mache: "🥗",
  roquette: "🥗",
  epinard: "🥬",
  blette: "🥬",
  poireau: "🥬",
  celeri: "🥬",
  fenouil: "🥬",
  artichaut: "🥬",
  asperge: "🥦",
  "haricot vert": "🫛",
  "petit pois": "🫛",
  feve: "🫛",
  courgette: "🥒",
  concombre: "🥒",
  aubergine: "🍆",
  poivron: "🫑",
  "poivron rouge": "🫑",
  "poivron vert": "🫑",
  "poivron jaune": "🫑",
  piment: "🌶️",
  oignon: "🧅",
  "oignon rouge": "🧅",
  echalote: "🧅",
  ail: "🧄",
  "ail rose": "🧄",
  poireau: "🥬",
  navet: "🥕",
  radis: "🥕",
  betterave: "🥕",
  panais: "🥕",
  topinambour: "🥕",
  mais: "🌽",
  "mais doux": "🌽",
  champignon: "🍄",
  shiitake: "🍄",
  girolles: "🍄",
  cepes: "🍄",
  pleurote: "🍄",
  truffe: "🍄",
  "pomme de terre": "🥔",
  "patate douce": "🥔",
  "pommes de terre": "🥔",
  gingembre: "🫚",
  curcuma: "🫚",

  // ── CONSERVES & SAUCES ──
  sauce: "🥫",
  "sauce tomate": "🥫",
  passata: "🥫",
  coulis: "🥫",
  conserve: "🥫",
  "boite de": "🥫",
  soupe: "🥣",
  veloute: "🥣",
  bouillon: "🥣",
  "fond de veau": "🥣",
  "fond de volaille": "🥣",
  haricot: "🥫",
  "maïs en boite": "🥫",
  "tomate concassee": "🥫",
  "tomates pelees": "🥫",
  pesto: "🫙",
  tapenade: "🫙",
  ketchup: "🍅",
  mayonnaise: "🫙",
  mayo: "🫙",
  moutarde: "🫙",
  "moutarde de dijon": "🫙",
  cornichon: "🫙",
  pickles: "🫙",
  huile: "🫙",
  "huile dolive": "🫙",
  "huile olive": "🫙",
  "huile tournesol": "🫙",
  "huile colza": "🫙",
  vinaigre: "🫙",
  "vinaigre balsamique": "🫙",
  "vinaigre cidre": "🫙",
  "sauce soja": "🫙",
  "nuoc mam": "🫙",
  tabasco: "🌶️",
  worcestershire: "🫙",
  "sauce worcestershire": "🫙",
  ravioli: "🫙",
  "lentille canard": "🫙",

  // ── BOISSONS ──
  eau: "💧",
  "eau plate": "💧",
  "eau gazeuse": "💧",
  perrier: "💧",
  badoit: "💧",
  evian: "💧",
  volvic: "💧",
  "san pellegrino": "💧",
  jus: "🥤",
  "jus orange": "🥤",
  "jus pomme": "🥤",
  "jus raisin": "🥤",
  "jus tomate": "🥤",
  smoothie: "🥤",
  nectar: "🥤",
  soda: "🥤",
  "coca cola": "🥤",
  coca: "🥤",
  pepsi: "🥤",
  sprite: "🥤",
  fanta: "🥤",
  orangina: "🥤",
  schweppes: "🥤",
  redbull: "🥤",
  monster: "🥤",
  "energy drink": "🥤",
  limonade: "🥤",
  sirop: "🍹",
  grenadine: "🍹",
  menthe: "🍹",
  cafe: "☕",
  capsule: "☕",
  nespresso: "☕",
  "dolce gusto": "☕",
  "cafe moulu": "☕",
  "cafe soluble": "☕",
  expresso: "☕",
  the: "🍵",
  "the vert": "🍵",
  "the noir": "🍵",
  "the blanc": "🍵",
  infusion: "🍵",
  tisane: "🍵",
  camomille: "🍵",
  verveine: "🍵",
  vin: "🍷",
  "vin rouge": "🍷",
  "vin blanc": "🍷",
  "vin rose": "🍷",
  biere: "🍺",
  "biere blonde": "🍺",
  "biere brune": "🍺",
  "biere sans alcool": "🍺",
  cidre: "🍺",
  champagne: "🍾",
  prosecco: "🍾",
  cremant: "🍾",
  mousseux: "🍾",
  whisky: "🥃",
  rhum: "🥃",
  vodka: "🥃",
  gin: "🥃",
  porto: "🍷",
  aperol: "🥃",

  // ── SNACKS & APERO ──
  chips: "🍟",
  "chips nature": "🍟",
  "chips paprika": "🍟",
  "chips piment": "🍟",
  pringles: "🍟",
  tuiles: "🍟",
  "monster munch": "🍟",
  cheetos: "🍟",
  "pop corn": "🍿",
  popcorn: "🍿",
  cacahuete: "🥜",
  "noix de cajou": "🥜",
  amande: "🥜",
  noisette: "🥜",
  noix: "🥜",
  pistache: "🥜",
  "noix macadamia": "🥜",
  "mix aperitif": "🥜",
  oleagineux: "🥜",
  "biscuit apero": "🍘",
  crackers: "🍘",
  gressins: "🍘",
  olives: "🫒",
  tarama: "🫙",
  houmous: "🫙",
  guacamole: "🥑",

  // ── SUCRERIES & DESSERTS ──
  biscuit: "🍪",
  cookie: "🍪",
  "petit beurre": "🍪",
  oreo: "🍪",
  speculoos: "🍪",
  "palets bretons": "🍪",
  sable: "🍪",
  gateau: "🎂",
  cake: "🎂",
  brownie: "🎂",
  madeleine: "🧁",
  cupcake: "🧁",
  muffin: "🧁",
  financier: "🧁",
  eclair: "🧁",
  chocolat: "🍫",
  tablette: "🍫",
  praline: "🍫",
  rocher: "🍫",
  bonbon: "🍬",
  caramel: "🍮",
  reglisse: "🍬",
  haribo: "🍬",
  confiture: "🍓",
  "confiture fraise": "🍓",
  "confiture abricot": "🍓",
  miel: "🍯",
  "pate a tartiner": "🍫",
  nutella: "🍫",
  "speculoos pate": "🍫",
  glace: "🍦",
  sorbet: "🍧",
  "glace vanille": "🍦",
  "glace chocolat": "🍦",
  compote: "🍎",
  "compote pomme": "🍎",
  dessert: "🍮",
  pudding: "🍮",
  "riz au lait": "🍮",
  tiramisu: "🍮",
  sucre: "🧂",
  "sucre glace": "🧂",
  "sucre roux": "🧂",
  cassonade: "🧂",
  stevia: "🧂",
  "miel dacacia": "🍯",
  "sirop erable": "🍯",
  levure: "🌾",
  "levure chimique": "🌾",
  bicarbonate: "🧂",
  vanille: "🫙",
  "extrait vanille": "🫙",
  gelatine: "🫙",

  // ── SURGELES ──
  surgele: "❄️",
  surgeles: "❄️",
  "pizza surgelee": "🍕",
  pizza: "🍕",
  "quiche surgelee": "❄️",
  "tarte surgelee": "❄️",
  feuillete: "❄️",
  nems: "❄️",
  "spring rolls": "❄️",
  nuggets: "❄️",
  "fish sticks": "❄️",
  "poisson pane": "❄️",
  "cordon bleu": "❄️",
  "hachis parmentier": "❄️",
  "legumes surgeles": "❄️",
  "epinards surgeles": "❄️",
  "petits pois surgeles": "❄️",
  "pommes dauphine": "❄️",
  "frites surgelees": "❄️",
  waffles: "❄️",
  buns: "❄️",
  "buns bolognaise": "❄️",

  // ── CONDIMENTS & EPICES ──
  sel: "🧂",
  "sel fin": "🧂",
  "gros sel": "🧂",
  "fleur de sel": "🧂",
  poivre: "🌶️",
  "poivre noir": "🌶️",
  "poivre blanc": "🌶️",
  paprika: "🌶️",
  piment: "🌶️",
  "piment despelette": "🌶️",
  curry: "🌶️",
  cumin: "🌶️",
  coriandre: "🌶️",
  curcuma: "🌿",
  cannelle: "🌿",
  "gingembre en poudre": "🌿",
  "noix de muscade": "🌿",
  herbes: "🌿",
  "herbes de provence": "🌿",
  thym: "🌿",
  romarin: "🌿",
  laurier: "🌿",
  basilic: "🌿",
  persil: "🌿",
  ciboulette: "🌿",
  estragon: "🌿",
  "menthe fraiche": "🌿",
  "ras el hanout": "🌿",
  "za atar": "🌿",
  "quatre epices": "🌿",
  "bouquet garni": "🌿",
  "levure de biere": "🌿",
  miso: "🫙",
  tahini: "🫙",

  // ── HYGIENE CORPORELLE ──
  dentifrice: "🦷",
  "brosse a dents": "🦷",
  "fil dentaire": "🦷",
  "bain de bouche": "🦷",
  shampooing: "🧴",
  "apres shampooing": "🧴",
  "apres-shampooing": "🧴",
  "masque cheveux": "🧴",
  "gel douche": "🧴",
  savon: "🧼",
  "savon liquide": "🧼",
  "pain de savon": "🧼",
  deodorant: "🧴",
  "anti transpirant": "🧴",
  parfum: "🧴",
  "crème visage": "🧴",
  "creme visage": "🧴",
  serum: "🧴",
  lotion: "🧴",
  demaquillant: "🧴",
  coton: "🧻",
  "coton tiges": "🧻",
  rasoir: "🪒",
  "mousse a raser": "🪒",
  "lame rasoir": "🪒",
  "protege slip": "🩱",
  "serviette hygienique": "🩱",
  tampon: "🩱",
  "coupe menstruelle": "🩱",

  // ── ENTRETIEN MAISON ──
  lessive: "🧺",
  "lessive liquide": "🧺",
  "lessive poudre": "🧺",
  "lessive capsules": "🧺",
  adoucissant: "🧺",
  "liquide vaisselle": "🧽",
  "tablette lave vaisselle": "🧽",
  "sel lave vaisselle": "🧽",
  "produit rinçage": "🧽",
  nettoyant: "🧹",
  "spray nettoyant": "🧹",
  "nettoyant wc": "🚽",
  "nettoyant salle de bain": "🧹",
  "nettoyant cuisine": "🧹",
  desinfectant: "🧹",
  javel: "🧹",
  "eau de javel": "🧹",
  vitre: "🧹",
  "nettoyant vitres": "🧹",
  "essuie tout": "🧻",
  sopalin: "🧻",
  "papier absorbant": "🧻",
  "papier toilette": "🚽",
  "papier wc": "🚽",
  "sac poubelle": "🗑️",
  "sac congelation": "🗑️",
  "film plastique": "🗑️",
  "papier aluminium": "🗑️",
  "papier cuisson": "🗑️",

  // ── BEBE ──
  couche: "👶",
  couches: "👶",
  "couche bebe": "👶",
  pampers: "👶",
  huggies: "👶",
  "lingette bebe": "🧻",
  "coton bebe": "🧻",
  biberon: "🍼",
  tetine: "🍼",
  sucette: "🍼",
  "lait maternise": "🍼",
  "lait bebe": "🍼",
  "lait 1er age": "🍼",
  "lait 2eme age": "🍼",
  "lait 3eme age": "🍼",
  "petits pots": "🥣",
  "compote bebe": "🍎",
  "puree bebe": "🥣",
  "cereales bebe": "🥣",
  "soupe bebe": "🥣",
  "crème bebe": "🧴",
  "creme bebe": "🧴",
  "huile bebe": "🧴",

  // ── PHARMACIE / SANTE ──
  medicament: "💊",
  paracetamol: "💊",
  doliprane: "💊",
  ibuprofene: "💊",
  advil: "💊",
  aspirine: "💊",
  vitamine: "💊",
  complement: "💊",
  thermometre: "🌡️",
  pansement: "🩹",
  bandage: "🩹",
  antiseptique: "🩺",
  alcool: "🩺",
  "eau oxygenee": "🩺",

  // ── ANIMAUX ──
  croquettes: "🐾",
  "pate pour chat": "🐾",
  "pate pour chien": "🐾",
  "nourriture chat": "🐾",
  "nourriture chien": "🐾",
  litiere: "🐾",
  "friandise chien": "🐾",
  "friandise chat": "🐾",
};

function getEmoji(name) {
  if (!name) return "🛒";
  const lower = name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

  // D'abord cherche une correspondance exacte (clés longues en priorité)
  const sortedKeys = Object.keys(EMOJIS).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    const normKey = key.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    if (lower.includes(normKey)) return EMOJIS[key];
  }
  return "🛒";
}

function guessCategory(name) {
  const l = name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
  if (
    /lait|yaourt|yogourt|fromage|beurre|creme|oeuf|viande|steak|poulet|dinde|canard|poisson|saumon|thon|jambon|charcuterie|saucisse|lardon/.test(
      l,
    )
  )
    return "Frais";
  if (/surgele|glace|sorbet|nugget|frite surgelee|pizza surgelee/.test(l)) return "Surgelés";
  if (/pain|baguette|brioche|viennoiserie|croissant/.test(l)) return "Boulangerie";
  if (/bebe|couche|biberon|maternise|lait 1er|lait 2eme|petit pot|puree bebe/.test(l)) return "Bébé";
  if (
    /shampooing|gel douche|savon|dentifrice|deodorant|lessive|vaisselle|nettoyant|essuie|toilette|lingette|rasoir|serviette hygienique|tampon|protege/.test(
      l,
    )
  )
    return "Hygiène";
  if (/eau|jus|soda|vin|biere|sirop|limonade|champagne|cidre|cafe|the|infusion|smoothie|redbull|monster/.test(l))
    return "Boissons";
  return "Épicerie";
}
